### ISSUE TITLE
"Add image" media selector not getting loaded when field is of a taxonomy

### ISSUE THREAD

**Issue by lexo-tfuerer** [lexo-ch/acf-image-focus#13]
If the ACF image focus field is on a taxonomy, the "Add image" button will not work, as the WordPress image selector (media popup) is unloaded. You can add a native ACF image field and click the "Add image" button there to load the image selector, after which the button will also work for the ACF image focus field.

![image](https://github.com/lexo-ch/acf-image-focus/assets/90773991/5d712024-084f-48a3-a85f-afecae662620)

**Comment by lexo-mpuzovic** [comment]
Resolved.
